### ISSUE TITLE
cursor not placed at all in editor after hitting enter - OSX

### ISSUE THREAD

**Issue by subhaze** [hahiserw/AceJump#1]
I just forked this and added the key mappings for OSX but sadly everything works fine aside from the cursor not being placed anywhere in the editor after hitting enter...

I've looked through the code but I'm not too keen on python or package development for Sublime Text so not sure where things are going wrong...

**Comment by hahiserw** [comment]
Damn, I wish I had a Mac. I added some 'print's which could help in debugging.
Is there some kind of warning in the console after hitting enter?
Did you try jumping with modifiers?

**Comment by subhaze** [comment]
Just checked the console and this is the output:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 200, in on_selection_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 199, in <lambda>
  File "./SublimeCodeIntel.py", line 841, in on_selection_modified
IndexError: Index out of range
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./AceJump.py", line 195, in run
Boost.Python.ArgumentError: Python argument types in
    Region.**init**(Region, float)
did not match C++ signature:
    **init**(_object*, long long)
    __init__(_object*, long long, long long, double)
    __init__(_object*, long long, long long)

**Comment by hahiserw** [comment]
It seems that there is a wrong region, but I have no idea what is causing it.
As soon as friend will be able to debug on Mac  I try something.
